---
title: "02_Laying_Out_an_App"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Layout

In this exercise, you'll pre-visualize your app and lay it out AWAY from the computer.

You will need some special tools for this session: a **paper** and **pencil** (or pen)

-   a sheet of printer paper makes a good proxy for a laptop display.
-   turn it horizontally ("landscape" format)
-   sketch out you widgets and your outputs
-   use your knowledge of Shiny Layouts
-   provide at least 3 different options, and then vote on the best option.
-   **spending** time *planning* **saves** you time *building*.

> Don't skip this process!

# Pick a Shiny Layout

-   Pick the Shiny layout that best corresponds to your app.

-   We want to use the summaries that we developed in part 1 (pick at least 3 from this collection):

    -   Total sales by county in terms of dollars

    -   Total sales by category name

    -   Most frequently sold counts of category names

    -   Create a variable that simplifies the categories. We choose "Whisky," "Vodka," "Rum," "Gin," "Liqueur" and "other," but you can choose your own.

        -   Summarize the count of sales by your simplified categories.

    -   Summarise the total sales by month for 2020

    -   Which of these can be represented by tables? Which might lend themselves to visualizations? We've provided one possible solution, but you can choose your own.

# Populate the Shiny layout with placeholders

-   populate that Shiny layout with placeholders.

    -   Just use simple components, like `p()`aragraphs or `h1()`, `h2()` , ... headers

# Making a theme

-   Also customize a theme for your app. To do this, use the `bslib()` package.

-   Copy the code from the bs-theme.app to make your theme interaction. Pick colors and fonts, and then be sure to **copy your theme customization** from the console into your app!

    -   Note: since we are using placeholders, you may not have all the widgets yet nor see their full theming. You may revisit this customization again later.
